# Generated by Django 5.2.7 on 2025-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfilter',
            name='arrival_airport_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchfilter',
            name='departure_airport_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
