# Generated by Django 5.2.7 on 2025-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtrip', '0002_searchfilter_arrival_airport_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfilter',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchfilter',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
