# Generated by Django 5.2.7 on 2025-10-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtrip', '0003_searchfilter_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfilter',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
